---
title: "概要"
subtitle: "労働経済学"
author: "川田恵介"
format:
  revealjs:
    incremental: true 
    slide-number: true
    html-math-method: katex
  pdf:
    pdf-engine: lualatex
    documentclass: ltjsarticle 
    toc: true
    toc-depth: 3
    number-sections: true
bibliography: "ref.bib"
---

- 「自身で労働経済学分野の実証論文を書く」技術を身につけることが目標

    - 実証手法/応用の理解に重点

    - [参考ページ](https://maxkasy.github.io/home/Labor_Oxford_2021/)

## 労働経済学

- 大きな関心は**労働市場**とそこに関連する現象の理解

    - 広義の家計内/企業内の意思決定 (結婚、出産、人事制度等)についての研究も多い
    
        - マクロ/人事/人口/家族の経済学との隣接分野
        
        - 最終的には**政策的含意**を得たい

- 大規模なデータを用いた、実証研究が中心

    - **統計モデルの定式化に対して、頑強な手法/解釈**を相対的に重視

## 労働市場

- 生産のみならず、分配にも決定的に影響

    - 大部分の現役家計は、労働所得に依存
    
        - $\iff$ 土地/金融市場

    - 不平等が大きな研究課題
    
- 労働力は異質性の大きな投入物

    - 買い手(企業)と売り手(労働者)のマッチングも主要論点

## 頑強な手法

- 比較的容易に大規模データへアクセス可能

    - よりデータ主導のアプローチが採用されやすい
    
- 集団の特徴解明や集団間の比較について、繊細に議論

    - 分析単位の"匿名性"が高い

    - 例: 中年男性は、中年女性に比べて、就業率が高い
    
        - $\iff$ (入門的)国際貿易: サウジアラビは原油を輸出

    - 一般に個人差が大きく、微妙な違いしか存在しない

    - 例: 平均的な中年男性よりも賃金が大きく高い/低い中年女性は、数多く存在

## 因果効果

- 政策的含意の中核

- 「社会になんらかの介入を行なう」ことの帰結は？

## 他科目との関連性

- 計量経済学との関連性が特に高い

    - 復習/実践における注意/実装/別解釈を提供
    
    - 計量経済学 II(北村周平, OSSIP)との関連性が最も強い
    
- 労働経済学に限らず、"データ分析"を学びたい受講者も歓迎

## R実習

- 講義を復習しながら、実際に分析コードを作成

- IDEとしては、以下の順番でおすすめ

    - R/Rstudio を自身のPCにインストール
    
    - Google colab (クラウド環境)
    
        - Google accountが必要

## 課題

- 合計３回のレポートにて成績を評価

- 過去の講義資料は[講義レポジトリ](https://github.com/tetokawata/EmpiricalLaborEconomics) から入手可能

## 参考文献

- オンライン
    
    - [CausalML](https://causalml-book.org/)

    - [作成中の日本語解説](https://tetokawata.github.io/BookEmiricalSocialML/)

- 紙

    - @aronow2019foundations
    
    - @angrist2009mostly

    - @angrist1999empirical


## Reference