---
title: "R入門: OLS"
format:
  revealjs:
    incremental: true 
    slide-number: true
    html-math-method: katex
  pdf:
    pdf-engine: lualatex
    documentclass: ltjsarticle 
    toc: true
    toc-depth: 3
    number-sections: true
execute: 
  warning: false
  message: false
  echo: true
---

## Quick example

- Robust standard errorを用いて信頼区間を計算する

```{r}
library(tidyverse)
library(lmtest)
library(sandwich)

Data = read_csv("CPS1985.csv")

Fit = lm(log(wage) ~ poly(experience,2) + education,
         Data)

coefci(Fit, vcov = vcovHC, type = "HC3")
```

## marginal

- 平均的なeducationのもとで、モデル上のwage-experienceの関係性を可視化

```{r}
library(ggeffects)

Pred = predict_response(
  Fit,
  "experience",
  vcov_fun = "vcovHC", 
  vcov_type = "HC3")

plot(Pred)
```

## 発展: pipe演算子

- 以下は同じ出力をもたらす

```{r}
#| eval: false
Data = read_csv("CPS1985.csv")

summary(Data)

read_csv("CPS1985.csv") |> 
  summary()
```

- functionA |> functionB: functionAの出力をfunctionBに入力する

    - Dataとして保存する必要がない

## bins plot

- $y\sim x$ の推定結果とbin plot

```{r}
Fig = Data |> 
  mutate(
    BinExp = ntile(experience,5),
    wage = log(wage)) |> 
  mutate(
    AveWage = mean(wage),
    AveExp = mean(experience),
    .by = c(BinExp)
  ) |> 
  ggplot(
    aes(
      x = experience,
      y = wage
    )
  ) +
  theme_bw() +
  geom_smooth(
    method = "lm",
    se = FALSE
  ) +
  geom_point(
    aes(
      x = AveExp,
      y = AveWage
    )
  )
```

## bins plot

- $y\sim x$ の推定結果とbin plot

```{r}
Fig
```


## bins plot

- $y\sim poly(x,2)$ の推定結果とbin plot

```{r}
Fig = Data |> 
  mutate(
    BinExp = ntile(experience,5),
    wage = log(wage)) |> 
  mutate(
    AveWage = mean(wage),
    AveExp = mean(experience),
    .by = c(BinExp)
  ) |> 
  ggplot(
    aes(
      x = experience,
      y = wage
    )
  ) +
  theme_bw() +
  geom_smooth(
    method = "lm",
    se = FALSE,
    formula = y ~ poly(x,2)
  ) +
  geom_point(
    aes(
      x = AveExp,
      y = AveWage
    )
  )
```

## bins plot

- $y\sim poly(x,2)$ の推定結果とbin plot

```{r}
Fig
```
