---
title: "序論"
subtitle: "労働経済学: 講義中はマイクはoffにしてください。チャットでの質問はいつでも歓迎です"
author: "川田恵介"
format:
  revealjs:
    incremental: true 
    slide-number: true
    bibliographystyle: apa
    html-math-method: katex
    chalkboard: true
  typst:
    fig-format: retina
    bibliographystyle: apa
    mainfont: "Hiragino Mincho ProN"
    number-sections: true
bibliography: "ref.bib"
execute:
  warning: false
  message: false
---

# 概要

## 目標

- 「自身で労働経済学分野の実証論文を書く」技術を身につけることが目標

    - 実証手法/応用の理解に重点
    
      - 分析工程への埋め込みを常に意識
      
    - 計量経済学の復習も複目標

- 実務における、「データを活用した意思決定」、を支援する技能習得につながることも期待

## 労働経済学

- 大きな関心は**労働市場**とそこに関連する現象の理解

    - 広義の家計/企業内の意思決定 (結婚、出産、人事制度等)についての研究も多い
    
        - マクロ/人事/人口/医療/教育/家族の経済学との隣接分野
        
        - 最終的には**政策的含意**を得たい

- 大規模なデータを用いた、実証研究が中心

    - **統計モデルの定式化に対して、頑強な手法/解釈**を相対的に重視

## 格差研究

- 労働市場は、生産のみならず、分配にも決定的に影響

    - 大部分の現役家計は、労働所得に依存
    
        - $\iff$ 土地/金融市場

    - 労働所得の改善や不平等の是正が大きな研究課題

## 因果効果

- 労働経済学における政策的議論の中核

  -「社会に対して、なんらかの介入を行なう」ことの帰結は？
  
    - 最低賃金、失業給付、解雇規制、自動化/国際貿易の帰結、等々

## 集団の特徴把握

- 個別事例の予測ではなく、集団の特徴解明や集団間の比較に注力する傾向

    - 分析単位の"匿名性"が高い

    - 例: 中年男性は、中年女性に比べて、就業率が高い
    
        - $\iff$ (入門的)国際貿易: サウジアラビは原油を輸出

- 一般に個人差が大きく、個人予測はかなり厳しい [@narayanan2024ai]

    - 例: 平均的な中年男性よりも賃金が大きく高い/低い中年女性は、数多く存在

## 頑強な推定手法

- 比較的容易に大規模データへアクセス可能

    - 研究者による詳細なモデル定式化ではなく、よりデータ主導のアプローチが採用されやすい
    
    - 現状、Semi-parametric推定の重要性が高まっている
    
      - 近年では機械学習の応用も注目を集める [@angrist2022machine]

## Quiz

- 教科書的な最尤推定やベイズ推定は、「母分布を有限個のパラメタでモデル化」し、モデルのパラメタを推定する

  - Parametric推定
  
- Semiparametric推定は、そのようなモデル化を行わない
  
- OLSはParametric/Semiparametric?

## 他科目との関連性

- 計量経済学との関連性が特に高い

    - 復習/実践における注意/実装/別解釈を提供
    
    - 特に"上級因果推論 (北村周平)" との関連性が強く、同時履修を強く推奨
    
- 本年度は、(統計的)機械学習も紹介

- 労働経済学に限らず、"データ分析"を学びたい受講者も歓迎

## R実習

- 講義を復習しながら、実際に分析コードを作成

- 演習環境としては、以下をサポート

    - R (バージョン 4.5.以降)
    
    - Rstudio (バージョン 2024.12.1+563以降) 
    
- 次回までに、自身のPCにインストールしてください

## 課題

- 合計３回のレポートにて成績を評価

- 過去の講義資料は[講義レポジトリ](https://github.com/tetokawata/EmpiricalLaborEconomics) から入手可能

## 参考文献

- 無料/オンライン
    
    - [CausalML](https://causalml-book.org/)

    - [バランス後の比較](https://github.com/tetokawata/NoteBalance)
    
    - [線形近似モデル](https://github.com/tetokawata/NoteBLP)

- 課金/紙

    - @aronow2019foundations
    
    - @angrist2009mostly

# 作業工程

## 議論の混乱

- "機械学習/OLSを用いると、因果効果を識別できる/できない"
  
  - 因果効果の識別と用いる推定手法は、本質的に別問題
  
- "機械学習を用いると、OLSよりも良いモデルが推定できる/できない"

  - そもそも良いモデルとは???

## 議論の整理

- 学術研究に期待される「建設的かつ丁寧な議論」のためには、議論の土台をしっかり論じることが重要

  - 議論の土台への認識がずれていると、ミスコミュニケーションが多発し、結果的に非効率

- 実証研究の方法論を議論する際には、まず前提となっている分析工程を整理することが有益

## 論点整理の方法

- 「研究目標について、データから回答する」を細分化した分析工程に落とし込む

  - 分析工程の中に、概念/手法を位置付ける

- 経済理論、因果推論や機械学習に対応可能な工程表に基づき議論 [@manski1995identification ; @lundberg2021your]

## 本講義の作業工程: 以下を設定

1. 研究目標 (Research question) $=$ 関心となる**社会 (Study Population)**の特徴

2. 推定目標 (Estimand) $=$ 研究目標に対応する**母集団 (Source Population)**の特徴

- 以上から「データが回答すべきこと」が明確化
    
3. 推定値 (Estimator) $=$ **データ**から推定目標の推論値の計算方法

4. コーディング $\rightarrow$ 推定結果 $\rightarrow$ 発信...

## 例: ゲームの因果効果: @egami2024causal

- 研究課題: ゲームは、健康状態を (因果的に) 悪化させるのか？

- 推定対象: コロナ下で生じた"ゲーム機購入権くじ参加者"について、居住地を含む背景属性の分布を均一化した後に、精神的健康状態の比較

- 推定値: 点推定量 $+$ 信頼区間 

  - 精神的健康状態は平均的に改善する明確な傾向が見られる

## 識別/推定

- 「研究目標、推定対象、推定値」の接続方法が重要

- 識別 (Identification) $$研究課題\underbrace{\iff}_{経済理論/因果推論などを用いた接続} 推定目標$$

- 推定 (Estimation/Inference/Learning) $$推定目標\underbrace{\iff}_{統計学/機械学習などを用いた接続} 推定値$$

## 例: ゲームの因果効果: @egami2024causal

- 研究課題: ゲームは、健康状態を（因果的に）悪化させるのか？

    - 識別: コロナ下で生じた「ゲーム機の過小供給」と、それに対応するための「購入券くじ」を自然実験として活用

- 推定対象: くじ引き参加者について、居住地を含む背景属性分布を均一化し、比較

    - 推定: Causal/Targeted Machine Learningを活用

- 推定値: 点推定量 $+$ 信頼区間

## まとめ

- 分析工程の全体像をまず把握することが重要

    - 伝統的な教科書は、特定のパートを焦点としていることに注意
    
        - "因果推論の教科書" $\rightarrow$ 識別が焦点
        
        - "統計学/機械学習の教科書" $\rightarrow$ 推定が焦点
        
        - "(労働)経済学の教科書" $\rightarrow$ 研究目標/識別が焦点

## Reference
